### ISSUE TITLE
Error: Can't resolve 'react-addons-shallow-compare'

### ISSUE THREAD

**Issue by meltingice** [MalucoMarinero/react-wastage-monitor#1]
Believe this package needs to be moved from `devDependencies` to regular dependencies since it's imported in `reuseChecker.js`

**Comment by thomasdavis** [comment]
Yeah, I can replicate, wasn't immediately obvious because I already had `react-addons-shallow-compare` installed.

**Comment by thomasdavis** [comment]
Fixed and published to npm@2.2.2. 

Thanks for the report!
