### ISSUE TITLE
Question about "StatelessComponent is impure"

### ISSUE THREAD

**Issue by traverse** [MalucoMarinero/react-wastage-monitor#2]
Hello,

Great tool but I have a question regarding the following:
![example](https://cloud.githubusercontent.com/assets/7240988/25889578/7cc5bc32-356a-11e7-8c24-37ed35e46023.png)
Is there any way to track down the `StatelessComponent`'s that are causing these logs? Working on quite a big project so it's difficult to track the components down manually as there are quite a few of them.

Cheers

**Comment by MalucoMarinero** [comment]
Hey there, the name is taken either from the React displayName or the constructor.name if the displayName is absent. In that instance we could probably update it to say who's calling it, that may help in locating it.

**Comment by traverse** [comment]
That might actually just work 👍

**Comment by MalucoMarinero** [comment]
0.2.3 version is up, that should help you find it. Long term we'll probably want to work towards some more comprehensive mode in DevTools or sometthing, so we can make it a bit denser with information and make it easierr to track what component is from where, but this should help you for now.

https://github.com/MalucoMarinero/react-wastage-monitor/commit/0807d3143b5f85bea50306ee6c9ada11e56c07d8

**Comment by traverse** [comment]
Works like a charm, looking forward to the future changes.
